# Test case inputs from test_daily_game()
day_number = 1
glasses_made = 10
signs_made = 2
price = 25
weather = 1
glasses_sold = 8
random_factor = 100

[previous_state]
current_assets = 200
total_profit = 0
day_count = 0
best_day_profit = 0
total_glasses_sold = 0
bankruptcy_count = 0

[final_state]
current_assets = 350
total_profit = 150
day_count = 1
best_day_profit = 150
total_glasses_sold = 8
bankruptcy_count = 0 